INSERT INTO games (game_date, total_teams, winning_team, losing_team)
VALUES
    ('2022-09-27', 19, 'Just OK', 'O-H-I-Know'),
    ('2022-10-04', 10, 'Just OK', 'Grin and Barret'),
    ('2022-10-11', 13, 'New Team, Who Dis?', 'Not Just OK'),
    ('2022-10-18', 1, 'Smart People', 'Just Not OK'),
    ('2022-10-25', 29, 'Just OK', 'Plus Ones');

INSERT INTO rounds (category, round_number, round_name, game_id)
VALUES
    ('picture', 1, 'Patterns', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('today in history', 2, 'Today or Tomorrow', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('sports', 3, 'NFL Teams', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('common bond', 4, 'Common Bond 1', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('general knowledge', 5, 'Mushrooms', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('audio', 6, 'It Takes Two', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('general knowledge', 7, 'Silly Rabbit', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('general knowledge', 8, 'Women Directors', (SELECT game_id from games where game_date='2022-09-27' LIMIT 1)),
    ('picture', 1, 'Famous Jameses', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('today in history', 2, 'Springtime', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('general knowledge', 3, 'Pints', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('general knowledge', 4, 'Ologies', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('general knowledge', 5, 'O-H I-O', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('audio', 6, 'Under the Covers', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('common bond', 7, 'Common Bond 2', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('general knowledge', 8, 'Units', (SELECT game_id from games where game_date='2022-10-04' LIMIT 1)),
    ('picture', 1, 'My Favorite Tartans', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('general knowledge', 2, 'Pumpkins', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('today in history', 3, 'Today in History', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('common bond', 4, 'Link', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('general knowledge', 5, 'Flags', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('audio', 6, 'Classical Music', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('general knowledge', 7, 'Name that Country', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('general knowledge', 8, 'Cryin'' all the time', (SELECT game_id from games where game_date='2022-10-11' LIMIT 1)),
    ('picture', 1, 'Cityscapes', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('sports', 2, 'Tom Brady', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('common bond', 3, 'Common Bond 3', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('general knowledge', 4, 'I Scream for Ice Cream', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('general knowledge', 5, 'Google', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('audio', 6, 'Bluegrass Brothers', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('general knowledge', 7, 'Monsters Inc.', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('general knowledge', 8, 'I cannot believe it is not butter', (SELECT game_id from games where game_date='2022-10-18' LIMIT 1)),
    ('picture', 1, 'Name that mustache', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('general knowledge', 2, 'Presidents', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('general knowledge', 3, 'Eggs for Days', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('general knowledge', 4, 'Who, indeed, framed Roger Rabbit?', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('general knowledge', 5, 'Famous Jimmies', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('audio', 6, 'All about that bass', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('today in history', 7, 'Nearly Halloween', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1)),
    ('general knowledge', 8, 'Istanbul (Not Constantinople)', (SELECT game_id from games where game_date='2022-10-25' LIMIT 1));

INSERT INTO questions (question, answer, total_correct_answers, round_id)
VALUES
    ('This is a question', 'This is an answer', 16, (SELECT round_id from rounds where round_name='Patterns' LIMIT 1)),
    ('This is a question', 'This is an answer', 10, (SELECT round_id from rounds where round_name='Today or Tomorrow' LIMIT 1)),
    ('This is a question', 'This is an answer', 5, (SELECT round_id from rounds where round_name='NFL Teams' LIMIT 1)),
    ('This is a question', 'This is an answer', 1, (SELECT round_id from rounds where round_name='Common Bond 1' LIMIT 1)),
    ('This is a question', 'This is an answer', 6, (SELECT round_id from rounds where round_name='Mushrooms' LIMIT 1)),
    ('This is a question', 'This is an answer', 12, (SELECT round_id from rounds where round_name='Silly Rabbit' LIMIT 1)),
    ('This is a question', 'This is an answer', 18, (SELECT round_id from rounds where round_name='Women Directors' LIMIT 1)),
    ('This is a question', 'This is an answer', 1, (SELECT round_id from rounds where round_name='Famous Jameses' LIMIT 1)),
    ('This is a question', 'This is an answer', 2, (SELECT round_id from rounds where round_name='Springtime' LIMIT 1)),
    ('This is a question', 'This is an answer', 3, (SELECT round_id from rounds where round_name='Pints' LIMIT 1)),
    ('This is a question', 'This is an answer', 4, (SELECT round_id from rounds where round_name='Ologies' LIMIT 1)),
    ('This is a question', 'This is an answer', 5, (SELECT round_id from rounds where round_name='O-H I-O' LIMIT 1)),
    ('This is a question', 'This is an answer', 6, (SELECT round_id from rounds where round_name='Under the Covers' LIMIT 1)),
    ('This is a question', 'This is an answer', 7, (SELECT round_id from rounds where round_name='Common Bond 2' LIMIT 1)),
    ('This is a question', 'This is an answer', 8, (SELECT round_id from rounds where round_name='Units' LIMIT 1)),
    ('This is a question', 'This is an answer', 13, (SELECT round_id from rounds where round_name='My Favorite Tartans' LIMIT 1)),
    ('This is a question', 'This is an answer', 12, (SELECT round_id from rounds where round_name='Pumpkins' LIMIT 1)),
    ('This is a question', 'This is an answer', 11, (SELECT round_id from rounds where round_name='Today in History' LIMIT 1)),
    ('This is a question', 'This is an answer', 10, (SELECT round_id from rounds where round_name='Link' LIMIT 1)),
    ('This is a question', 'This is an answer', 9, (SELECT round_id from rounds where round_name='Flags' LIMIT 1)),
    ('This is a question', 'This is an answer', 8, (SELECT round_id from rounds where round_name='Classical Music' LIMIT 1)),
    ('This is a question', 'This is an answer', 7, (SELECT round_id from rounds where round_name='Name that Country' LIMIT 1)),
    ('This is a question', 'This is an answer', 6, (SELECT round_id from rounds where round_name='Cryin'' all the time' LIMIT 1)),
    ('This is a question', 'This is an answer', 0, (SELECT round_id from rounds where round_name='Cityscapes' LIMIT 1)),
    ('This is a question', 'This is an answer', 1, (SELECT round_id from rounds where round_name='Tom Brady' LIMIT 1)),
    ('This is a question', 'This is an answer', 0, (SELECT round_id from rounds where round_name='Common Bond 3' LIMIT 1)),
    ('This is a question', 'This is an answer', 1, (SELECT round_id from rounds where round_name='I Scream for Ice Cream' LIMIT 1)),
    ('This is a question', 'This is an answer', 0, (SELECT round_id from rounds where round_name='Google' LIMIT 1)),
    ('This is a question', 'This is an answer', 1, (SELECT round_id from rounds where round_name='Bluegrass Brothers' LIMIT 1)),
    ('This is a question', 'This is an answer', 2, (SELECT round_id from rounds where round_name='Monsters Inc.' LIMIT 1)),
    ('This is a question', 'This is an answer', 1, (SELECT round_id from rounds where round_name='I cannot believe it is not butter' LIMIT 1)),
    ('This is a question', 'This is an answer', 4, (SELECT round_id from rounds where round_name='Name that mustache' LIMIT 1)),
    ('This is a question', 'This is an answer', 8, (SELECT round_id from rounds where round_name='Presidents' LIMIT 1)),
    ('This is a question', 'This is an answer', 12, (SELECT round_id from rounds where round_name='Eggs for Days' LIMIT 1)),
    ('This is a question', 'This is an answer', 16, (SELECT round_id from rounds where round_name='Who, indeed, framed Roger Rabbit?' LIMIT 1)),
    ('This is a question', 'This is an answer', 20, (SELECT round_id from rounds where round_name='Famous Jimmies' LIMIT 1)),
    ('This is a question', 'This is an answer', 24, (SELECT round_id from rounds where round_name='All about that bass' LIMIT 1)),
    ('This is a question', 'This is an answer', 28, (SELECT round_id from rounds where round_name='Nearly Halloween' LIMIT 1)),
    ('This is a question', 'This is an answer', 0, (SELECT round_id from rounds where round_name='Istanbul (Not Constantinople)' LIMIT 1));
